add stalebot for issues
grafana/grafana-aws-sdk-react pull request #84
Opened 2024-05-31 19:41 UTC by katebrenner

part of https://github.com/grafana/oss-plugin-partnerships/issues/915

2024-05-31 21:02 UTC, iwysiu reviewed
Should this file be empty?

2024-06-04 11:47 UTC, sarahzinger requested changes
ooops! empty file, feel free to re-request when it's ready!

2024-06-04 18:13 UTC, katebrenner commented
awk! updated :)

2024-06-04 18:22 UTC, iwysiu approved these changes

2024-06-05 17:52 UTC, sarahzinger approved these changes

2024-06-06 19:18 UTC, merged